---
components:
  - name: led_strip
    description: RMT-based driver for WS2812B/SK6812/APA106/SM16703 LED strips
    group: led
    groups: []
    code_owners: UncleRus
    depends:
      - name: driver
      - name: log
      - name: color
      - name: esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp32s2
      - name: esp32c3
    licenses:
      - name: MIT
    copyrights:
      - author:
          name: UncleRus
        year: 2020
