# Install script for directory: C:/Espressif/frameworks/esp-idf-v4.4.2

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/Ezlo_Pi_v2x")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "C:/Espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-objdump.exe")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_ringbuf/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/efuse/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_ipc/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/driver/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_pm/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/mbedtls/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/bootloader/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esptool_py/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/partition_table/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/app_update/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/bootloader_support/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/spi_flash/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/nvs_flash/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/pthread/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_gdbstub/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/espcoredump/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_phy/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_system/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_rom/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/hal/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/vfs/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_eth/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/tcpip_adapter/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_netif/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_event/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/wpa_supplicant/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_wifi/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ieee802154/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/console/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/openthread/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/lwip/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/log/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/heap/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/soc/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_hw_support/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/xtensa/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp32s3/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_common/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_timer/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/freertos/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/newlib/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/cxx/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/app_trace/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/asio/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/bt/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/cbor/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/unity/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/cmock/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/coap/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/nghttp/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp-tls/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_adc_cal/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_hid/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/tcp_transport/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_http_client/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_http_server/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_https_ota/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_https_server/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_lcd/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/protobuf-c/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/protocomm/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/mdns/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_local_ctrl/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/sdmmc/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_serial_slave_link/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/esp_websocket_client/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/expat/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/wear_levelling/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/fatfs/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/freemodbus/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/idf_test/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/jsmn/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/json/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/libsodium/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/mqtt/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/openssl/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/perfmon/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/spiffs/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/usb/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/tinyusb/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ulp/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/wifi_provisioning/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/trace/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_nvs/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_hal/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_cloud/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/common_components/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/library/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_actions/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_event_queue/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_timer/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_cloud_constants/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/gpio_isr_service/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/digital_io/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/frozen/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/aes_lib/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_factory_info/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/version/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/qt_serial/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_wifi/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_websocket_client/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_http/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/data/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/devices/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/scenes/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/registration/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/favorite/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/gateways/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/info/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/modes/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/room/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/settings/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/network/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/feature/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/web_provisioning/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/items/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/sensor_pir/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/sensor_bme280/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/sensor_door/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/dimmable_bulb/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/joystick_2_axis/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ultrasonic_HC_SR04/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/sensor_touch_tpp_223b/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ultrasonic_MB1013/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/servo_motor_MG_996R/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/025_sens_ldr_digital_module/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/026_sens_ldr_analog_sensor/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/027_sens_water_sensor/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/028_sens_i2c_accelerometer/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ir_blaster_tools/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/IR_Blaster_encoder_decoder/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/IR_Blaster_data_operation/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/029_IR_blaster_remote/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_devices/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_ble/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/timer_service/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_ble_service/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/main/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/sensor_dht11/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ezlopi_config/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/certificates/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/ssd1306/cmake_install.cmake")
  include("C:/Users/soc20/Ezlo_IR_Blaster/firmware/ezlopi/115200/esp-idf/uuid/cmake_install.cmake")

endif()

