#ifndef _EZLOPI_CORE_BOARDS_H_
#define _EZLOPI_CORE_BOARDS_H_

#define EZLOPI_AMBIENT_TRACKER_PRO_REV_A 1

#define EZLOPI_BOARD_TYPE EZLOPI_AMBIENT_TRACKER_PRO_REV_A

#endif //  _EZLOPI_CORE_BOARDS_H_
