#ifndef __EZLOPI_METHODS_STR_H__
#define __EZLOPI_METHODS_STR_H__

/*****************************************************************************************
 *                                     Methods                                           *
 *****************************************************************************************/
extern const char *method_hub_item_updated;
extern const char *method_add_device;
extern const char *method_add_all_devices;
extern const char *method_cloud_firmware_info_get;
// extern const  char *method_cloud_access_keys_controller_sync;
// extern const  char *method_cloud_timezones_get
// extern const  char *method_cloud_controller_abstracts_set;
// extern const  char *method_cloud_controller_abstracts_list;
// extern const  char *method_cloud_storage_controller_token;
// extern const  char *method_extensions_plugin_info_installed;
// extern const  char *method_extensions_plugin_install_execute;
// extern const  char *method_extensions_plugin_install_request;
// extern const  char *method_extensions_plugin_run ;
// extern const  char *method_extensions_plugin_uninstall_execute ;
// extern const  char *method_extensions_plugin_uninstall_request ;
// extern const  char *method_hub_offline_credentials_updated;
// extern const  char *method_hub_bridge_controller_connection_list ;
// extern const  char *method_hub_bridge_controller_connection_set ;
// extern const  char *method_hub_coordinates_get ;
// extern const  char *method_hub_coordinates_set;
// extern const  char *method_hub_description_set;
// extern const  char *method_hub_device_force_remove ;
// extern const  char *method_hub_device_firmware_update ;
extern const char *method_hub_devices_list;
// extern const  char *method_hub_device_armed_set ;
// extern const  char *method_hub_device_name_set  ;
// extern const  char *method_hub_device_room_set ;
// extern const  char *method_hub_device_setting_dictionary_value_set ;
// extern const  char *method_hub_device_setting_value_set ;
// extern const  char *method_hub_gateway_setting_value_set ;
// extern const  char *method_hub_detection_device_add;
// extern const  char *method_hub_detection_devices_list ;
// extern const  char *method_hub_detection_device_remove ;
// extern const  char *method_hub_detection_device_set ;
// extern const  char *method_hub_setting_updated ;
// extern const  char *method_hub_device_setting_reset ;
// extern const  char *method_hub_device_settings_list;
// extern const  char *method_hub_setting_value_set_request;
// extern const  char *method_hub_setting_value_reset_request ;
extern const char *method_hub_device_setting_updated;
// extern const  char *method_hub_extensions_plugin_info_installed ;
// extern const  char *method_hub_extensions_plugin_install_execute ;
// extern const  char *method_hub_software_update_execute ;
// extern const  char *method_hub_extensions_plugin_install_request ;
// extern const  char *method_hub_extensions_plugin_run ;
// extern const  char *method_hub_extensions_plugin_uninstall_execute;
// extern const  char *method_hub_extensions_plugin_uninstall_request;
extern const char *method_hub_favorite_list;
extern const char *method_hub_favorite_set;
extern const char *method_hub_firmware_update;
extern const char *method_hub_info_get;
extern const char *method_hub_data_value_list_request;
extern const char *method_hub_settings_list_request;
extern const char *method_hub_features_list;
extern const char *method_hub_feature_status_set;
extern const char *method_hub_gateways_list;
extern const char *method_hub_geteway_settings_list;
extern const char *method_hub_item_dictionary_clear;
extern const char *method_hub_item_dictionary_value_add;
extern const char *method_hub_item_dictionary_value_remove;
extern const char *method_hub_items_list;
extern const char *method_hub_item_dictionary_value_set;
extern const char *method_hub_item_value_set;
extern const char *method_hub_item_value_percent_apply;
extern const char *method_hub_modes_get;
// extern const  char *method_hub_modes_current_get;
// extern const  char *method_hub_modes_switch ;
// extern const  char *method_hub_modes_switch_to_delay_set;
// extern const  char *method_hub_modes_alarm_delay_set ;
// extern const  char *method_hub_modes_alarms_off_add ;
// extern const  char *method_hub_modes_alarms_off_remove;
// extern const  char *method_hub_modes_switch_cancel ;
// extern const  char *method_hub_modes_notification_add;
// extern const  char *method_hub_modes_notificationnotifyallset ;
// extern const  char *method_hub_modes_notifications_set;
// extern const  char *method_hub_modes_notification_remove;
// extern const  char *method_hub_modes_disarmed_default_set;
// extern const  char *method_hub_modes_disarmed_devices_add;
// extern const  char *method_hub_modes_disarmed_devices_remove;
// extern const  char *method_hub_network_reset ;
// extern const  char *method_hub_network_wifi_scan_start ;
// extern const  char *method_hub_network_wifi_scan_stop ;
extern const char *method_hub_reset;
// extern const  char *method_hub_log_remote_set;
// extern const  char *method_hub_log_local_set;
extern const char *method_hub_network_get;
extern const char *method_hub_version_get;
extern const char *method_hub_provision_info_set;
extern const char *method_hub_room_all_delete;
extern const char *method_hub_room_create;
extern const char *method_hub_room_delete;
extern const char *method_hub_room_image_set;
extern const char *method_hub_room_get;
extern const char *method_hub_room_list;
extern const char *method_hub_room_name_set;
// extern const  char *method_hub_room_order_set;
// extern const  char *method_hub_room_view_set;
// extern const  char *method_hub_server_request;
// extern const  char *method_hub_time_location_get;
// extern const  char *method_hub_time_location_set;
extern const char *method_hub_time_location_list;
// extern const  char *method_hub_software_info_get;
extern const char *method_register;
extern const char *method_registered;
// extern const  char *method_hub_devices_service_notifications_set ;
extern const char *method_hub_reboot;
// extern const  char *method_hub_offline_login_hub;
// extern const  char *method_hub_offline_login_ui ;
// extern const  char *method_hub_network_enabled_set ;
// extern const  char *method_hub_detection_devices_scan_start;
// extern const  char *method_hub_detection_devices_scans_top;
extern const char *method_hub_scene_run_progress;
extern const char *ezlopi_rpc_method_notfound_str;
extern const char *ezlopi_hub_scene_changed_str;
extern const char *ezlopi_hub_scene_added_str;
extern const char *ezlopi_hub_scene_deleted_str;

extern const char *ezlopi_hub_room_created_str;
extern const char *ezlopi_hub_room_edited_str;
extern const char *ezlopi_hub_room_deleted_str;
extern const char *ezlopi_hub_room_reordered_str;

#endif // __EZLOPI_METHODS_STR_H__