
#ifndef __EZLOPI_CLOUD_STRS_
#define __EZLOPI_CLOUD_STRS_

extern const char *ezlopi_underscore_str;
extern const char *ezlopi_dot_str;
extern const char *ezlopi_undefined_str;


/******************** Categories strings start *********************/
extern const char *ezlopi_interface_str;
extern const char *ezlopi_dimmable_str;
extern const char *ezlopi_light_str;
extern const char *ezlopi_switch_str;
extern const char *ezlopi_security_str;
extern const char *ezlopi_sensor_str;
extern const char *ezlopi_generic_str;
// extern const char *ezlopi_hvac_str;
// extern const char *ezlopi_camera_str;
extern const char *ezlopi_door_str;
extern const char *ezlopi_lock_str;
// extern const char *ezlopi_window_str;
// extern const char *ezlopi_cov_str;
// extern const char *ezlopi_remote_str;
// extern const char *ezlopi_control_str;
extern const char *ezlopi_ir_str;
extern const char *ezlopi_tx_str;
// extern const char *ezlopi_io_str;
// extern const char *ezlopi_serial_str;
// extern const char *ezlopi_port_str;
// extern const char *ezlopi_scene_str;
// extern const char *ezlopi_controller_str;
// extern const char *ezlopi_av_str;
extern const char *ezlopi_humidity_str;
extern const char *ezlopi_temperature_str;
// extern const char *ezlopi_zwave_str;
// extern const char *ezlopi_int_str;
// extern const char *ezlopi_insteon_str;
// extern const char *ezlopi_power_str;
extern const char *ezlopi_meter_str;
// extern const char *ezlopi_alarm_str;
// extern const char *ezlopi_panel_str;
// extern const char *ezlopi_patrtition_str;
// extern const char *ezlopi_siren_str;
extern const char *ezlopi_weather_str;
// extern const char *ezlopi_philips_str;
// extern const char *ezlopi_appliance_str;
// extern const char *ezlopi_uv_str;
// extern const char *ezlopi_mouse_str;
// extern const char *ezlopi_trap_str;
// extern const char *ezlopi_doorbell_str;
// extern const char *ezlopi_keypad_str;
// extern const char *ezlopi_garage_str;
extern const char *ezlopi_flow_str;
// extern const char *ezlopi_voltage_str;
extern const char *ezlopi_state_str;
extern const char *ezlopi_level_str;
extern const char *ezlopi_clock_str;
/******************** Categories strings end *********************/

/******************** Item name strings start *********************/
extern const char *ezlopi_acceleration_str;
extern const char *ezlopi_x_str;
extern const char *ezlopi_y_str;
extern const char *ezlopi_z_str;
extern const char *ezlopi_axis_str;
extern const char *ezlopi_status_str;
extern const char *ezlopi_operation_str;
extern const char *ezlopi_user_str;
extern const char *ezlopi_code_str;
extern const char *ezlopi_dw_str;
extern const char *ezlopi_handle_str;
extern const char *ezlopi_latch_str;
extern const char *ezlopi_emergency_str;
extern const char *ezlopi_initialization_str;
extern const char *ezlopi_unattended_str;
extern const char *ezlopi_safety_str;
extern const char *ezlopi_beam_str;
extern const char *ezlopi_obstacle_str;
extern const char *ezlopi_problem_str;
extern const char *ezlopi_short_str;
extern const char *ezlopi_circuit_str;
extern const char *ezlopi_fail_str;
extern const char *ezlopi_events_str;
extern const char *ezlopi_test_str;
extern const char *ezlopi_maintainance_str;
extern const char *ezlopi_sounding_str;
extern const char *ezlopi_sound_str;
extern const char *ezlopi_list_str;
extern const char *ezlopi_volume_str;
extern const char *ezlopi_select_str;
extern const char *ezlopi_playback_str;
extern const char *ezlopi_periodic_str;
extern const char *ezlopi_inspection_str;
extern const char *ezlopi_heat_str;
extern const char *ezlopi_color_str;
extern const char *ezlopi_transition_str;
extern const char *ezlopi_changes_str;
extern const char *ezlopi_intrusion_str;
extern const char *ezlopi_tempering_str;
extern const char *ezlopi_cover_str;
extern const char *ezlopi_glass_str;
extern const char *ezlopi_breakage_str;
extern const char *ezlopi_move_str;
extern const char *ezlopi_impact_str;
extern const char *ezlopi_invalid_str;
extern const char *ezlopi_smoke_str;
extern const char *ezlopi_dust_str;
extern const char *ezlopi_in_str;
extern const char *ezlopi_filter_str;
extern const char *ezlopi_replacement_str;
extern const char *ezlopi_pump_str;
extern const char *ezlopi_master_str;
extern const char *ezlopi_rain_str;
extern const char *ezlopi_moisture_str;
extern const char *ezlopi_freeze_str;
extern const char *ezlopi_ac_str;
extern const char *ezlopi_surge_str;
extern const char *ezlopi_drop_str;
extern const char *ezlopi_drift_str;
extern const char *ezlopi_over_str;
extern const char *ezlopi_load_str;
extern const char *ezlopi_error_str;
extern const char *ezlopi_charging_str;
extern const char *ezlopi_backup_str;
extern const char *ezlopi_atmospheric_str;
extern const char *ezlopi_barometric_str;
extern const char *ezlopi_hw_str;
extern const char *ezlopi_sw_str;
extern const char *ezlopi_shutoff_str;
extern const char *ezlopi_digital_str;
extern const char *ezlopi_input_str;
extern const char *ezlopi_remaining_str;
extern const char *ezlopi_time_str;
extern const char *ezlopi_basic_str;
extern const char *ezlopi_dew_str;
extern const char *ezlopi_point_str;
extern const char *ezlopi_down_str;
extern const char *ezlopi_stop_str;
extern const char *ezlopi_up_str;
extern const char *ezlopi_direction_str;
extern const char *ezlopi_distance_str;
extern const char *ezlopi_electric_str;
extern const char *ezlopi_ampere_str;
extern const char *ezlopi_kvah_str;
extern const char *ezlopi_kvar_str;
extern const char *ezlopi_kvarh_str;
extern const char *ezlopi_kwh_str;
extern const char *ezlopi_factor_str;
extern const char *ezlopi_pulse_str;
extern const char *ezlopi_volt_str;
extern const char *ezlopi_watt_str;
extern const char *ezlopi_resist_str;
extern const char *ezlopi_heating_str;
extern const char *ezlopi_cooling_str;
extern const char *ezlopi_energy_str;
extern const char *ezlopi_loudness_str;
extern const char *ezlopi_lux_str;
extern const char *ezlopi_reset_str;
extern const char *ezlopi_rgbcolor_str;
extern const char *ezlopi_rotation_str;
extern const char *ezlopi_threat_str;
extern const char *ezlopi_seismic_str;
extern const char *ezlopi_intensity_str;
extern const char *ezlopi_magnitude_str;
extern const char *ezlopi_rate_str;
extern const char *ezlopi_command_str;
extern const char *ezlopi_soil_str;
extern const char *ezlopi_solar_str;
extern const char *ezlopi_radiation_str;
extern const char *ezlopi_temp_str;
extern const char *ezlopi_fan_str;
extern const char *ezlopi_mode_str;
extern const char *ezlopi_saving_str;
extern const char *ezlopi_operating_str;
extern const char *ezlopi_setpoint_str;
extern const char *ezlopi_tide_str;
extern const char *ezlopi_ultraviolet_str;
extern const char *ezlopi_codes_str;
extern const char *ezlopi_action_str;
extern const char *ezlopi_scan_str;
extern const char *ezlopi_progress_str;
extern const char *ezlopi_velocity_str;
extern const char *ezlopi_weight_str;
extern const char *ezlopi_air_str;
extern const char *ezlopi_tank_str;
extern const char *ezlopi_capacity_str;
extern const char *ezlopi_electrical_str;
extern const char *ezlopi_resistivity_str;
extern const char *ezlopi_conductivity_str;
extern const char *ezlopi_frequency_str;
extern const char *ezlopi_period_str;
extern const char *ezlopi_boiler_str;
extern const char *ezlopi_domestic_str;
extern const char *ezlopi_hot_str;
extern const char *ezlopi_outside_str;
extern const char *ezlopi_exhaust_str;
extern const char *ezlopi_oxidation_str;
extern const char *ezlopi_reduction_str;
extern const char *ezlopi_potential_str;
extern const char *ezlopi_chlorine_str;
extern const char *ezlopi_acidity_str;
extern const char *ezlopi_heart_str;
extern const char *ezlopi_lf_str;
extern const char *ezlopi_hf_str;
extern const char *ezlopi_ratio_str;
extern const char *ezlopi_particulate_str;
extern const char *ezlopi_matter_str;
extern const char *ezlopi_str_dot_str;
extern const char *ezlopi_program_str; 
extern const char *ezlopi_failures_str;
extern const char *ezlopi_sleep_str;
extern const char *ezlopi_apnea_str;
extern const char *ezlopi_stage_str;
extern const char *ezlopi_voc_str;
extern const char *ezlopi_rf_str;
extern const char *ezlopi_signal_str;
extern const char *ezlopi_strength_str;
extern const char *ezlopi_basal_str;
extern const char *ezlopi_metabolic_str;
extern const char *ezlopi_body_str;
extern const char *ezlopi_mass_str;
extern const char *ezlopi_index_str;
extern const char *ezlopi_total_str;
extern const char *ezlopi_fat_str;
extern const char *ezlopi_muscle_str;
extern const char *ezlopi_relative_str;
extern const char *ezlopi_modulation_str;
extern const char *ezlopi_respiratory_str;
extern const char *ezlopi_density_str;
extern const char *ezlopi_salinity_str;
extern const char *ezlopi_reactivity_str;
extern const char *ezlopi_volatile_str;
extern const char *ezlopi_organic_str;
extern const char *ezlopi_compound_str;
extern const char *ezlopi_methane_str;
extern const char *ezlopi_radon_str;
extern const char *ezlopi_concentration_str;
extern const char *ezlopi_formaldehyde_str;
extern const char *ezlopi_weekly_str;
extern const char *ezlopi_intervals_str;
extern const char *ezlopi_daily_str;
extern const char *ezlopi_goto_str;
extern const char *ezlopi_favorite_str;
extern const char *ezlopi_zones_str;
extern const char *ezlopi_activity_str;
extern const char *ezlopi_bed_str;
extern const char *ezlopi_ammonia_str;
extern const char *ezlopi_applied_str;
extern const char *ezlopi_force_str;
extern const char *ezlopi_on_str;
extern const char *ezlopi_bone_str;
extern const char *ezlopi_condenser_str;
extern const char *ezlopi_coil_str;
extern const char *ezlopi_defrost_str;
extern const char *ezlopi_discharge_str;
extern const char *ezlopi_line_str;
extern const char *ezlopi_evaporator_str;
extern const char *ezlopi_lead_str;
extern const char *ezlopi_liquid_str;
extern const char *ezlopi_nitrogen_str;
extern const char *ezlopi_dioxide_str;
extern const char *ezlopi_ozone_str;
extern const char *ezlopi_return_str;
extern const char *ezlopi_suction_str;
extern const char *ezlopi_sulfur_str;
extern const char *ezlopi_supply_str;
extern const char *ezlopi_send_str;
extern const char *ezlopi_learn_str;
extern const char *ezlopi_magnetic_str;
extern const char *ezlopi_gyroscope_str;
extern const char *ezlopi_fingerprint_str;
extern const char *ezlopi_ids_str;
extern const char *ezlopi_particles_str;
extern const char *ezlopi_um_str;
/******************** Item name strings end *********************/

/******************** Device type strings start *********************/
extern const char *ezlopi_device_str;
extern const char *ezlopi_motion_str;
// extern const char *ezlopi_multisensor_str;
// extern const char *ezlopi_bulb_str;
// extern const char *ezlopi_strip_str;
// extern const char *ezlopi_thermostat_str;
extern const char *ezlopi_outlet_str;
extern const char *ezlopi_dimmer_str;
extern const char *ezlopi_inwall_str;
// extern const char *ezlopi_multi_str;
// extern const char *ezlopi_repeater_str;
// extern const char *ezlopi_shutter_str;
// extern const char *ezlopi_valve_str;
// extern const char *ezlopi_roller_str;
// extern const char *ezlopi_portable_str;
// extern const char *ezlopi_panic_str;
// extern const char *ezlopi_mousetrap_str;
extern const char *ezlopi_transmetter_str;
/******************** Device type strings end *********************/

/******************** Device strings start *********************/
extern const char *ezlopi_alarms_str;
extern const char *ezlopi_button_str;
extern const char *ezlopi_leak_str;
extern const char *ezlopi_water_str;
extern const char *ezlopi_tilt_str;
extern const char *ezlopi_thermostats_str;
extern const char *ezlopi_gas_str;
extern const char *ezlopi_angle_str;
extern const char *ezlopi_position_str;
extern const char *ezlopi_athmo_str;
extern const char *ezlopi_pressure_str;
extern const char *ezlopi_aux_str;
extern const char *ezlopi_binary_str;
extern const char *ezlopi_barrier_str;
extern const char *ezlopi_battery_str;
extern const char *ezlopi_co2_str;
extern const char *ezlopi_co_str;
extern const char *ezlopi_current_str;
extern const char *ezlopi_multilevel_str;
/******************** Device strings end *********************/

#endif // __EZLOPI_CLOUD_STRS_


