#ifndef _EZLOPI_SETTINGS_H_
#define _EZLOPI_SETTINGS_H_

#include <stdbool.h>

typedef enum
{
    EZLOPI_SETTINGS_ACTION_GET_SETTING,
    EZLOPI_SETTINGS_ACTION_SET_SETTING,
    EZLOPI_SETTINGS_ACTION_RESET_SETTING,
    EZLOPI_SETTINGS_ACTION_UPDATE_SETTING,
    EZLOPI_SETTINGS_ACTION_MAX
} e_ezlopi_settings_action_t;

#endif // _EZLOPI_SETTINGS_H_
