#ifndef __EZLOPI_CLOUD_ENUMS_H__
#define __EZLOPI_CLOUD_ENUMS_H__

typedef enum e_ezlopi_lock_operations
{
    EZLOPI_LOCK_NONE,
    EZLOPI_LOCK_OPERATION,
    EZLOPI_UNLOCK_OPERATION,
    EZLOPI_RF_LOCK_OPERATION,
    EZLOPI_RF_UNLOCK_OPERATION,
    EZLOPI_KEYPAD_LOCK_OPERATION,
    EZLOPI_KEYPAD_UNLOCK_OPERATION,
    EZLOPI_MANUAL_NOT_FULLY_LOCKED_OPERATION,
    EZLOPI_RF_NOT_FULLY_LOCKED_OPERATION,
    EZLOPI_AUTO_LOCK_NOT_FULLY_LOCKED_OPERATION,
    EZLOPI_UNLOCK_BY_RF_WITH_INVALID_USER_CODE,
    EZLOPI_LOCK_BY_RF_WITH_INVALID_USER_CODE,
    EZLOPI_LOCK_JAMMED,
    EZLOPI_UNKNOWN,
    EZLOPI_LOCK_OPERATION_MAX,
} e_ezlopi_lock_operations_t;

#endif // __EZLOPI_CLOUD_ENUMS_H__