#ifndef _EZLOPI_CORE_SCENES_SCRIPTS_CUSTOM_LIBS_INCLUDES_H_
#define _EZLOPI_CORE_SCENES_SCRIPTS_CUSTOM_LIBS_INCLUDES_H_

#ifdef CONFIG_EZPI_SERV_ENABLE_MESHBOTS

#include "corelib.h"

#endif  // CONFIG_EZPI_SERV_ENABLE_MESHBOTS
#endif // _EZLOPI_CORE_SCENES_SCRIPTS_CUSTOM_LIBS_INCLUDES_H_
