#ifndef __EZLOPI_CLOUD_KEYWORDS_H__
#define __EZLOPI_CLOUD_KEYWORDS_H__

#include "stdio.h"
// extern const  char *ezlopi_ezlopi_str;
extern const char *ezlopi__str;
extern const char *ezlopi_id_str;
extern const char *ezlopi_ids_str;
extern const char *ezlopi__id_str;
extern const char *ezlopi_device_id_str;
extern const char *ezlopi_device_ids_str;
extern const char *ezlopi_sender_str;
extern const char *ezlopi_name_str;
extern const char *ezlopi_value_str;
extern const char *ezlopi_key_method_str;
extern const char *ezlopi_msg_id_str; // message counter, number of data transferred to ezlopi-cloud
extern const char *ezlopi_msg_subclass_str;
extern const char *ezlopi_ui_broadcast_str;
extern const char *ezlopi_result_str;
extern const char *ezlopi_params_str;
extern const char *ezlopi_gateway_id_str;
extern const char *ezlopi_scene_id_str;
extern const char *ezlopi_scene_name_str;
extern const char *ezlopi_status_str;
extern const char *ezlopi_userNotification_str;
extern const char *ezlopi_notifications_str;
extern const char *ezlopi_room_id_str;
extern const char *ezlopi_room_name_str;
extern const char *ezlopi_error_str;
extern const char *ezlopi_expressions_str;
extern const char *ezlopi_is_group_str;
extern const char *ezlopi_user_notifications_str;
extern const char *ezlopi_house_modes_str;
extern const char *ezlopi_blockOptions_str;
extern const char *ezlopi_version_str;
extern const char *ezlopi_args_str;
extern const char *ezlopi_delay_str;
extern const char *ezlopi_fields_str;
extern const char *ezlopi_blockType_str;
extern const char *ezlopi_when_str;
extern const char *ezlopi_enabled_str;
extern const char *ezlopi_group_id_str;
extern const char *ezlopi_parent_id_str;
extern const char *ezlopi_then_str;
extern const char *ezlopi_else_str;
extern const char *ezlopi_hasGetter_str;
extern const char *ezlopi_hasSetter_str;
extern const char *ezlopi_show_str;
extern const char *ezlopi_hwaddr_str;
extern const char *ezlopi_internetAvailable_str;
extern const char *ezlopi_network_str;
extern const char *ezlopi_wan_str;
extern const char *ezlopi_wifi_str;
extern const char *ezlopi_up_str;
extern const char *ezlopi_interfaces_str;
extern const char *ezlopi_auto_str;
extern const char *ezlopi_type_str;
extern const char *ezlopi_ip_str;
extern const char *ezlopi_mask_str;
extern const char *ezlopi_gateway_str;
extern const char *ezlopi_mode_str;
extern const char *ezlopi_dhcp_str;
extern const char *ezlopi_ipv4_str;
extern const char *ezlopi_gateways_str;
extern const char *ezlopi_label_str;
extern const char *ezlopi_yes_str;
extern const char *ezlopi_no_str;
extern const char *ezlopi_ready_str;
extern const char *ezlopi_not_ready_str;
extern const char *ezlopi_settings_str;
extern const char *ezlopi_valueType_str;
extern const char *ezlopi_metadata_str;
extern const char *ezlopi_code_str;
extern const char *ezlopi_data_str;
extern const char *ezlopi_message_str;
extern const char *ezlopi_Unknown_method_str;
extern const char *ezlopi_firmware_str;
extern const char *ezlopi_null_str;
extern const char *ezlopi_firmware_version_str;
extern const char *ezlopi_uptime_str;
extern const char *ezlopi_mac_str;
extern const char *ezlopi_uuid_str;
extern const char *ezlopi_firmware_type_str;

#endif // __EZLOPI_CLOUD_KEYWORDS_H__
