name: create bin

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
#    - name: esp-idf sdkconfig
#      uses: espressif/esp-idf-ci-action@v1
#      with:
#        esp_idf_version: v4.4
#        path: 'firmware/ezlopi'
#        command: 'idf.py set-target esp32'
#    - name: Enable Bluetooth in project configuration
#      run: |
#        echo "CONFIG_BT_ENABLED=y" >> firmware/ezlopi/sdkconfig.defaults
#        echo "CONFIG_BLUEDROID_ENABLED=y" >> firmware/ezlopi/sdkconfig.defaults
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        path: 'firmware/ezlopi'
        target: esp32s3
        
    - name: Save build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ezlopi.bin
        path: 'firmware/ezlopi/build/ezlopi.bin'
